homepage:
    pattern:  /
    defaults: { _controller: BesttecSADBundle:Default:index }
    
novooficio:
    pattern:  /novooficio
    defaults: { _controller: BesttecSADBundle:Default:novooficio }
    
historico:
    pattern:  /historico
    defaults: { _controller: BesttecSADBundle:Default:historico }
    
geraroficio:
    pattern:  /geraroficio
    defaults: { _controller: BesttecSADBundle:Default:geraroficio }
    methods: [POST]
