parameters:
#    besttec_sad.example.class: Besttec\SAD\Bundle\Example

services:
#    besttec_sad.example:
#        class: %besttec_sad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
